name: deploy
on:
  push:
    branches:
      - main
    pull_request:
      branches:
        - main
      types: [opened, synchronize, reopened]
permissions:
  contents: read
  pull-requests: write
  issues: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      build:
        - uses: actions/checkout@v3
        - name: Restore node_modules cache
          uses: actions/cache@v3
          with:
            path: |
              ~/.npm
              ${{ github.workspace }}/node_modules
              ${{ github.workspace }}/.next/cache
            key: ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-${{ hashFiles('**/*.js', '**/*.jsx', '**/*.ts', '**/*.tsx') }}
        - name: Install dependencies
          run: yarn install --frozen-lockfile --prefer-offline
        - name: Lint check
          run: yarn lint
        - name: Build
          run: yarn build
        - name: Upload artifact
          uses: actions/upload-artifact@v2
          with:
            path: build
      deploy:
        if: github.ref_name == "main"
        environment:
          name: github-pages
          url: ${{ steps.deploy.outputs.url }}
        runs-on: ubuntu-latest
        needs: build
        steps:
          - name: Deploy to GitHub Pages
            id: deploy
            uses: actions/deploy@-pages@v2